name: unit tests check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pw
          POSTGRES_DB: rldb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[dev]'

      - name: Setup Tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Run unit tests
        env:
          DB_URI: "postgresql+psycopg2://postgres:pw@localhost:5432/rldb"
        run: |
          pytest --cov=recordlinker --cov-report=xml tests/unit


