name: unit tests check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pw
          POSTGRES_DB: testdb

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[dev]'

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -U postgres; do sleep 1; done

      - name: Run unit tests
        env:
          MPI_DB_TYPE: postgres
          MPI_DBNAME: postgres
          MPI_HOST: localhost
          MPI_PORT: 5432
          MPI_USER: postgres
          MPI_PASSWORD: pw
        run: |
          pytest --cov=recordlinker --cov-report=xml tests/unit
